[build]
  command = "npm install --force && npm run build"
  publish = "D:/angular/stock-angular/stock/dist/stock/browser"

# Remove the following functions section entirely if you're not using any functions:
 [functions]
   directory = "D:/angular/stock-angular/stock/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
